### ISSUE TITLE
[Feature] - gRPC로 로그인, 회원가입 기능 구현하기

### ISSUE THREAD

**Issue by didskfo** [Teeam-Sync/Sync-Server#3]
### Task Description
gRPC를 사용하여 로그인, 회원가입 기능 구현하기

### Task
- [ ] 이메일, 패스워드 기반 회원가입 구현하기
- [ ] 이메일, 패스워드 기반 로그인 구현하기 
- [ ] mongodb atlas 연결하기
- [ ] 패스워드 SHA256 기반으로 해싱하여 저장하기
